### ISSUE TITLE
`https://go.microsoft.com/fwlink/?linkid=839822&clcid=0x409` does not download latest version

### ISSUE THREAD

**Issue by missingcharacter** [Azure/Azure-Data-Factory-Integration-Runtime-in-Windows-Container#18]
When I go to `https://go.microsoft.com/fwlink/?linkid=839822&clcid=0x409` I am now downloading version `5.30.8555.1` when latest version is `5.32.8597.5`, according to https://www.microsoft.com/en-us/download/details.aspx?id=39717

### Screenshot of `https://go.microsoft.com/fwlink/?linkid=839822&clcid=0x409`

![image](https://github.com/Azure/Azure-Data-Factory-Integration-Runtime-in-Windows-Container/assets/728243/974d0aa2-f5d5-44a7-8b72-2b2d61fd75ed)

### Screenshot of `https://www.microsoft.com/en-us/download/details.aspx?id=39717`

![image](https://github.com/Azure/Azure-Data-Factory-Integration-Runtime-in-Windows-Container/assets/728243/ace28775-eaa1-4aa4-b2b5-e910e472cafb)

**Comment by byran77** [comment]
Hi @missingcharacter,
sorry for the late reply. The link is by design redirected to the auto-upgraded version (that is, the most stable version), instead of the latest version. For instance, we now start to push version 5.32.8600.2, and the fwlink will help you download this version.
![image](https://github.com/Azure/Azure-Data-Factory-Integration-Runtime-in-Windows-Container/assets/69568467/022009f7-ff85-4e7f-905c-ffb5c5c616cc)

The recommended way to get the latest version is going download center.

**Comment by missingcharacter** [comment]
Thanks, @byran77. I will close this
